### ISSUE TITLE
Support multiple top-level/content folders with user roles/access

### ISSUE THREAD

**Issue by Webreaper** [Webreaper/Damselfly#236]
Might be nice to allow multiple mounts in Docker so that more than one root folder can be added. This would probably require:

1. Setup / config with a browser where you select folders you want to index
2. Folder/role associations (or folder/user associations)

So that user1 could access folder1 and folder2, and user2 could access folder2 and folder3.

**Comment by sawasy** [comment]
Mutliple directories (in Docker) for `/pictures` would be useful. I am bolting this on to NextCloud which has a `photos` directory and an `InstantUploads` directory, for automated device syncing, which are in the top level directory.  It would be nice to index both.

m!

**Comment by Webreaper** [comment]
The best way to do this right now would be to create a third folder, point Damselfly at that, and put two symlinks in so you have two subfolders, one for `photos` and one for `InstantUploads`.

**Comment by sawasy** [comment]
I got this hack to work, but there is a bit of a sharp corner. You must define the underlying volume in `docker-compose.yaml`.

```
      - /var/www/nextcloud/data/<USERID>/files/damselfly:/pictures
      - /var/www/nextcloud/data/<USERID>/files:/var/www/nextcloud/data/<USERID>/files
 ```

As the symlinks won't be able to travers the full or relative path provided by the symlink.

Not a huge deal, but it took a min of head scratching.

Thanks for the idea!


m!

**Comment by bericha** [comment]
I'm in the same boat as sawasy. I created a symlink for my nextcloud InstandUploads directory into my top level Damselfly directory. Damselfly is not seeing the symlink listed. Did the following to create and verify that the symlink is in the directory:

root@RHVH01:~# ln -s /mnt/user/appdata/nextcloud/brichards/files/InstantUpload/Camera /mnt/user/Media/Pictures
root@RHVH01:/mnt/user/Media/Pictures# ls
2010/  2011/  2013/  2014/  2015/  2016/  2017/  2018/  2019/  **Camera@**  To\ print/  ben_phone/

**Comment by lightbender255** [comment]
# **Windows**
## SymLinks

In a PowerShell with Administrator privilege run the following:
```powershell
New-Item -ItemType Junction -Path "g-assets" -Target "g:\Assets"`
```

Use something like this for the docker-compose.yaml:
_It may be a terrible idea to map the roots of the drives but it saved a lot of typing for me._
```yaml
version: "3"
services:
  damselfly:
    container_name: damselfly
    image: webreaper/damselfly
    ports:
      - "6363:6363/tcp"
    volumes:
      - "G:/docker-storage/damselfly:/config"
      - "G:/docker-storage/damselfly/thumbs:/thumbs"
      - "G:/docker-storage/damselfly/dir_links:/pictures"
      - "C:/:/mnt/host/c"
      - "G:/:/mnt/host/g"
    restart: unless-stopped
```
