### ISSUE TITLE
Any way to access Nextcloud data folder?

### ISSUE THREAD

**Issue by janaxhell** [Webreaper/Damselfly#473]
I am trying to deploy Damselfly on Docker, but I don't know how to mount Nextcloud Photos folder as /pictures, because it has mandatory root permissions. While with Photoprism I just had to mount the path and it worked fine, with Damselfly I get "failed to deploy a stack: (root) Additional property damselfly is not allowed" error when I try to deploy the stack with the same exact path. 
The volume is local, on same machine where I have both Nextcloud and Photoprism.
This is the compose I'm trying to use:
```
damselfly: 
        container_name: damselfly
        image: webreaper/damselfly
        ports:
            - 6363:6363/tcp
        volumes:
            - /srv/dev-disk-by-uuid-8998116d-e145-4319-8c9f-41609747f657/Configs/damselfly:/config
            - /srv/dev-disk-by-uuid-8998116d-e145-4319-8c9f-41609747f657/Configs/damselfly/thumbs:/thumbs
            - /srv/dev-disk-by-uuid-ba4514c7-4c36-4c08-9827-3f3f584ab6b0/data/nextcloud/jan_axhell/files/Photos/DCIM:/pictures 
        restart: unless-stopped
```

**Comment by Webreaper** [comment]
Sorry, don't know the answer to this - I don't know anything about Nextcloud. This sounds like a docker error to me. Is the above your entire docker file? If so, googling for the error you're getting indicates it's malformed and missing the services tag.

See here: 

https://stackoverflow.com/questions/38717025/docker-compose-file-is-invalid-additional-properties-not-allowed

**Comment by janaxhell** [comment]
Yes, you are right, I usually do that, but since the error mentioned "root" I thought it was a permission problem. It was not, your link enlightened me: I did copy the docker-compose in your Installation section as-is, and just modified volume paths, not noticing that it was missing 
```
version: '3'
  services:
```
at the beginning. So Portainer was whining about that (despite not showing any red alert in compose window). As soon as I added those lines, it worked fine.
The number 3 is arbitrary, I just tried it and it worked, but I have no idea which should be the "correct" one.

So my whole compose now looks like this:
```
version: '3'
  services:
      damselfly:
        container_name: damselfly
        image: webreaper/damselfly
        ports:
            - 6363:6363/tcp
        volumes:
            - /srv/dev-disk-by-uuid-8998116d-e145-4319-8c9f-41609747f657/Configs/damselfly:/config
            - /srv/dev-disk-by-uuid-8998116d-e145-4319-8c9f-41609747f657/Configs/damselfly/thumbs:/thumbs
            - /srv/dev-disk-by-uuid-ba4514c7-4c36-4c08-9827-3f3f584ab6b0/data/nextcloud/jan_axhell/files/Photos/DCIM:/pictures 
        restart: unless-stopped
```
