### ISSUE TITLE
Damselfly keeps crashing

### ISSUE THREAD

**Issue by gouthamravee** [Webreaper/Damselfly#528]
Damselfly version:  v4.1.3.0

docker compose 
```
services:
  damselfly:
    container_name: damselfly
    image: webreaper/damselfly
    network_mode: host
    environment:
      - TZ="America/New_York"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./thumbs:/thumbs
      - /mnt/photography:/pictures
    restart: unless-stopped
```

I added my whole 1.8TB photography collection to damselfly and I keep seeing messages like what you see below. I have AI object detection and face recognition turned off. Thumbnail generation is running. 

Damselfly is running in docker, inside a Debian based VM in proxmox. The VM has 20 cores and 15GB of ram assigned to it. 

Do these errors just mean damselfly doesn't have the thumbnails for the images yet? Is that related to the 'killed' message, and what seems like a crash. Ram usage is very low, only about 9% of total ram is being actively used. 

```
damselfly  | [03:04:09.670-.NET TP Worker-ERR] Unable to process /thumb/Large/47038: Object reference not set to an instance of an object.
damselfly  | [03:04:09.674-.NET TP Worker-ERR] Thumbnail conversion failed for /pictures/Lightroom CC/3da420dce54846ac9a5ef36da157ce47/originals/2024/2024-04-20/_DSC1910.dng: Object reference not set to an instance of an object.
damselfly  | [03:04:09.701-.NET TP Worker-ERR] Unable to process /thumb/Large/47490: Object reference not set to an instance of an object.
damselfly  | Killed
damselfly exited with code 137
damselfly  | Preparing to start Damselfly....
```
