### ISSUE TITLE
Unable to change Damselfly's port

### ISSUE THREAD

**Issue by Badwolf369** [Webreaper/Damselfly#534]
My compose file is set up like so:
```yml
services:
  damselfly-dev:
    container_name: damselfly-dev
    image: webreaper/damselfly
    ports:
      - 8081:81/tcp
    volumes:
      - S:/media-server/dev-photos-damselfly/services/damselfly:/config
      - S:/media-server/dev-photos-damselfly/services/damselfly/thumbs:/thumbs
      - S:/media-server/dev-photos-damselfly/library:/pictures
    restart: unless-stopped
```
This is the dev instance which runs on port `8081`. This is so experimental config changes dont affect the main instance on port `6363`. However, navigating to `localhost:8081` gets an `ERR_EMPTY_RESPONSE`. Also, with Damselfly running on port `8081` only, navigating to `localhost:6363` displays the damselfly loading page, but it never loads. When running one instance on `8081` and one on `6363`, the instance on `6363` works as expected.
