### ISSUE TITLE
No images showing.  How to map folder properly?

### ISSUE THREAD

**Issue by jill88** [Webreaper/Damselfly#548]
This time, i am using a docker instance in Ubuntu.  Here is my compose file, and the folders are properly mounted, but nothing is showing in Damselfly interface.  Any suggestions? Thank you.

```
services:
 damselfly: 
        container_name: damselfly
        image: webreaper/damselfly
        ports:
            - 6363:6363/tcp
        volumes:
            - ./config:/config
            - ./thumbs:/thumbs
            - /mnt/winshare1/photoshare1:/pictures 
        restart: unless-stopped

```
